---
- name: install build depends
  apt:
    pkg: "{{ item }}"
    state: present
    install_recommends: no
    update_cache: yes
  with_items:
    - build-essential
    - git
    - libcurl4-openssl-dev
    - libreadline-dev
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev
    - zlib1g-dev
  sudo: true
  tags:
    - rbenv

